general:
    logLevel: INFO #[optional]
    attributes_to_read:
        - TSurf
        - Albedo
        - WindSpd
        # - T
        # - LatentHeatFlux
    projectName: kartoza #also used for workspacename in Geoserver 
    height_levels: [0.3,10.5,40.5]
    inputFile: ./inputFiles/MZ_Flow_2018-07-22_05.00.00-new.nc #MZ_Flow_2018-07-22_05.00.00.nc #BVOC_Mainz_IsoOff_2018-07-06_05.00.00.nc #MZ_Flow_2018-07-22_05.00.00.nc #NewSimulation_2018-06-23_05.00.00.nc # #NewSimulation_2018-06-23_05.00.00.nc # #NewSimulation_2018-06-23_05.00.00.nc #BVOC_Mainz_IsoOff_2018-07-06_05.00.00.nc #NewSimulation_2018-06-23_05.00.00.nc
geoserver:
    url: http://localhost:8600/geoserver
    uploadTimeOut: 20 
frontend:
    path: ./frontend/app #[optional]
    projectHandling: True #If multiple Geoserver Instances are used the projectHandling does not work (If active Deletion of not found workspaces)
styles: #To be defined in Hex Color Code
    DefaultColors: ["#0571b0","#92c5de","#f7f7f7","#f4a582","#ca0020"]
    customStyles:
        Albedo: #[optional]
            colors: ["#000000","#ffffff"]
            values: [0,1] #[optional]
